"""create categoria table

Revision ID: e0b3f3d59de3
Revises: d581fb20e3cd
Create Date: 2024-11-04 14:29:25.371097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b3f3d59de3'
down_revision: Union[str, None] = 'd581fb20e3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('nome')
    )
    op.drop_table('categorias')
    op.drop_constraint('atletas_categoria_id_fkey', 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'categoria', ['categoria_id'], ['pk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key('atletas_categoria_id_fkey', 'atletas', 'categorias', ['categoria_id'], ['pk_id'])
    op.create_table('categorias',
    sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk_id', name='categorias_pkey'),
    sa.UniqueConstraint('nome', name='categorias_nome_key')
    )
    op.drop_table('categoria')
    # ### end Alembic commands ###
